### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by rbmelolima** [iuricode/ensinando-frontend#1]
Podemos abrir um markdown com links úteis de documentações, roadmaps para os iniciantes saberem onde buscar conhecimento?

Eu particularmente não tenho tempo pra escrever o básico do básico mas queria ajudar também esse repositório.

Abraços!

**Comment by iuricode** [comment]
Boa ideia irmão, está disposto a fazer isso e ajuda a comunidade? É que no momento estou escrevendo o modulo CSS, vou lançar ele no domingo!

**Comment by rbmelolima** [comment]
Acabei aqui e já fiz a PR, dá uma olhadinha ai

**Comment by iuricode** [comment]
Caraca, show de bola! Vai ajudar muito a comunidade, obrigado irmão!

**Comment by iuricode** [comment]
Se tiver mais ideias vai manda na issues e depois da uma PR.
